// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
export {}
        
declare module 'vue' {
  export interface GlobalComponents {
    GoodbyeWorld: typeof import('./src/components/GoodbyeWorld.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    VApp: typeof import('vuetify/lib')['VApp']
  }
}
