// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
export {}
        
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/components/app.vue')['default']
    GoodbyeWorld: typeof import('./src/components/GoodbyeWorld.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomePage: typeof import('./src/components/home-page.vue')['default']
    NotFoundPage: typeof import('./src/components/not-found-page.vue')['default']
    PlaybillPage: typeof import('./src/components/playbill/playbill-page.vue')['default']
    PlayEditorPage: typeof import('./src/components/play-editor/play-editor-page.vue')['default']
    PromiseBtn: typeof import('./src/components/widgets/promise-btn.vue')['default']
    VAlert: typeof import('vuetify/lib')['VAlert']
    VApp: typeof import('vuetify/lib')['VApp']
    VAppBar: typeof import('vuetify/lib')['VAppBar']
    VAppBarTitle: typeof import('vuetify/lib')['VAppBarTitle']
    VAvatar: typeof import('vuetify/lib')['VAvatar']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCol: typeof import('vuetify/lib')['VCol']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VDivider: typeof import('vuetify/lib')['VDivider']
    VFooter: typeof import('vuetify/lib')['VFooter']
    VImg: typeof import('vuetify/lib')['VImg']
    VList: typeof import('vuetify/lib')['VList']
    VListItem: typeof import('vuetify/lib')['VListItem']
    VListItemAvatar: typeof import('vuetify/lib')['VListItemAvatar']
    VListItemContent: typeof import('vuetify/lib')['VListItemContent']
    VListItemSubtitle: typeof import('vuetify/lib')['VListItemSubtitle']
    VListItemTitle: typeof import('vuetify/lib')['VListItemTitle']
    VMain: typeof import('vuetify/lib')['VMain']
    VRow: typeof import('vuetify/lib')['VRow']
    VSpacer: typeof import('vuetify/lib')['VSpacer']
    VSubheader: typeof import('vuetify/lib')['VSubheader']
    VToolbarTitle: typeof import('vuetify/lib')['VToolbarTitle']
    VTooltip: typeof import('vuetify/lib')['VTooltip']
  }
}
