name: Deploy to Firebase on merge to release branch
'on':
  push:
    branches:
      - release
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install-all && yarn build
      - uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PLAYWRIGHT_PROD }}

